trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    wget https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.deb
    sudo dpkg -i hugo_0.55.6_Linux-64bit.deb
  displayName: 'Install dependencies'

- script: |
    hugo check
    hugo
    echo $(hugo version)
  displayName: 'Check and build'
