baseURL = "https://ondetem.de"
languageCode = "pt-br"
title = "Onde Tem"
theme = "hugo-creative-portfolio-theme"
googleAnalytics = "UA-143396256-1"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "green"
  description = "Onde encontrar produtos amados pelos brasileiros na Alemanha"
  copyright = "&copy;2019 A Firma GmbH"
  sidebarAbout = [
    "Frustado por não encontrar os produtos brasileiros que você ama?",
    "Esse problema acabou."
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "mediz@ondetem.de"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "produtos/"
  home = true

  [[params.navlinks]]
  name = "Sobre"
  url = "sobre/"

  [[params.navlinks]]
  name = "Fale Conosco"
  url = "contato/"

  [params.social]
  email         = "mediz@ondetem.de"
  instagram     = "https://instagram.com/ondetememberlim"
