name: OndeTem CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.2.1
      with:
        hugo-version: 'latest'
    - name: Compress Images
      uses: docker://calibreapp/github-image-actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: |
        hugo check
        hugo --gc --minify --cleanDestinationDir
        echo $(hugo version)
